# Generated by Django 5.1.2 on 2024-10-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Default', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='Default', max_length=200),
        ),
    ]
