# Generated by Django 5.1.2 on 2024-10-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_desc_item_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/1377/1377194.png', max_length=500),
        ),
    ]
